set_property SRC_FILE_INFO {cfile:C:/Users/SCL/Clock_div/Clock_div.srcs/constrs_1/new/cons.xdc rfile:../../../Clock_div.srcs/constrs_1/new/cons.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V11 [get_ports outclk]
