# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/a.xdc

# Block Designs: bd/mux4x1/mux4x1.bd
# Block Designs: The module: 'mux4x1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/mux4x1/ip/mux4x1_notGate_3bit_0_0/mux4x1_notGate_3bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_notGate_3bit_0_0 || ORIG_REF_NAME==mux4x1_notGate_3bit_0_0} -quiet] -quiet

# IP: bd/mux4x1/ip/mux4x1_notGate_3bit_0_1/mux4x1_notGate_3bit_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_notGate_3bit_0_1 || ORIG_REF_NAME==mux4x1_notGate_3bit_0_1} -quiet] -quiet

# IP: bd/mux4x1/ip/mux4x1_andGate_3bit_0_0/mux4x1_andGate_3bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_andGate_3bit_0_0 || ORIG_REF_NAME==mux4x1_andGate_3bit_0_0} -quiet] -quiet

# IP: bd/mux4x1/ip/mux4x1_andGate_3bit_0_1/mux4x1_andGate_3bit_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_andGate_3bit_0_1 || ORIG_REF_NAME==mux4x1_andGate_3bit_0_1} -quiet] -quiet

# IP: bd/mux4x1/ip/mux4x1_andGate_3bit_0_2/mux4x1_andGate_3bit_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_andGate_3bit_0_2 || ORIG_REF_NAME==mux4x1_andGate_3bit_0_2} -quiet] -quiet

# IP: bd/mux4x1/ip/mux4x1_andGate_3bit_0_3/mux4x1_andGate_3bit_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_andGate_3bit_0_3 || ORIG_REF_NAME==mux4x1_andGate_3bit_0_3} -quiet] -quiet

# IP: bd/mux4x1/ip/mux4x1_orGate_3bit_2_0_0/mux4x1_orGate_3bit_2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mux4x1_orGate_3bit_2_0_0 || ORIG_REF_NAME==mux4x1_orGate_3bit_2_0_0} -quiet] -quiet

# XDC: bd/mux4x1/mux4x1_ooc.xdc
